### ISSUE TITLE
little confused

### ISSUE THREAD

**Issue by rakibtg** [acelaya/php-persistent-login#1]
Hi @acelaya i was looking through your repository, on the composer file the description is "A package that provides an abstraction layer to manage persistent login sessions in PHP applications"
what did you mean by "abstraction layer to manage persistent login"?
Thanks

**Comment by acelaya** [comment]
In programming, an abstraction layer is something you can use to abstract from the real implementation of something else.
What I meant to say is that this library provides a common API to manage persistent login in different scopes, with integration with different frameworks and libraries.

However, this is an unfinished project.

**Comment by rakibtg** [comment]
Thanks for the explanation, i was trying to add the symphony auth provider on a raw PHP project but seems like a mess.. anyhow, do you have any plan to finish this project?

**Comment by acelaya** [comment]
Yes, I would like to, but I was having some problems to integrate my
approach with psr-7 frameworks.
I will probably finish it some day, but I wouldn't expect it soon.

2016-04-02 9:01 GMT+02:00 Hasan notifications@github.com:

> Thanks for the explanation, i was trying to add the symphony auth provider
> on a raw PHP project but seems like a mess.. anyhow, do you have any plan
> to finish this project?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/acelaya/php-persistent-login/issues/1#issuecomment-204660166

## 

Alejandro Celaya Alastrué
http://www.alejandrocelaya.com
